config/routes.rb
Rails.application.routes.draw do
  
   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  resources :trees
  get 'home/index'
  get 'home/pricing'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "home#index"
  
   devise_scope :user do
     get "/users/sign_out" => "devise/sessions#destroy"
   end
end 

app/views/layouts/_navBar.html.erb
<%= stylesheet_link_tag "navbar"%>

<nav class="navbar">
  <%= link_to root_path, class: "navbar-logo" do %>
    <%= image_tag("tree.png", alt: "LinkTree Logo", class: "logo-image") %>
    <span class="logo-text">Branched</span>
  <% end %>
  
  <div class="navbar-links">
    <%= link_to "Pricing", home_pricing_path , class: "nav-link login-link" %>
    <% if user_signed_in? %>
      <%= link_to "My Trees", trees_path, class: "nav-link" %>
      <%= link_to "New Tree", new_tree_path, class: "nav-link" %>
      <%= link_to "Log out", "/users/sign_out", class: "nav-link logout-link" %>
      <%= link_to "My account", edit_user_registration_path, class: "nav-link"%>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "nav-link signup-link" %>
      <%= link_to "Log in", new_user_session_path, class: "nav-link login-link" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinktreeClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navBar"%>
    <%= yield %>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/layouts/trees.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Branched - Your Custom Link Tree</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "trees", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navBar" %>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>